"""Named, closed limits for untrusted candidate input."""

PDF_MAX_BYTES = 10 * 1024 * 1024
PDF_MAX_PAGES = 30
TXT_MAX_BYTES = 2 * 1024 * 1024
AUDIO_MAX_BYTES = 25 * 1024 * 1024
AUDIO_MAX_DURATION_SECONDS = 15 * 60
BROWSER_RECORDING_MAX_DURATION_SECONDS = 15 * 60
TEXT_MAX_CODEPOINTS = 30_000

MAX_UPLOAD_COUNT = 8
UPLOAD_CHUNK_BYTES = 1024 * 1024
MULTIPART_MAX_PARTS = MAX_UPLOAD_COUNT + 1
MULTIPART_MAX_BOUNDARY_BYTES = 200
MULTIPART_MAX_HEADER_BYTES_PER_PART = 8 * 1024
MULTIPART_MAX_HEADERS_PER_PART = 16
MULTIPART_MAX_TEXT_BYTES = TEXT_MAX_CODEPOINTS * 4
MULTIPART_MAX_OVERHEAD_BYTES = 256 * 1024
MULTIPART_MAX_TOTAL_BYTES = (
    MAX_UPLOAD_COUNT * AUDIO_MAX_BYTES
    + MULTIPART_MAX_TEXT_BYTES
    + MULTIPART_MAX_OVERHEAD_BYTES
)

# Roughly fifty visible characters on an A4/Letter page. Pages below this
# density are rendered for OCR; denser pages keep their embedded text layer.
PDF_TEXT_DENSITY_THRESHOLD = 0.0001
PDF_OCR_DPI = 200
PDF_OCR_TIMEOUT_SECONDS = 120
PDF_MAX_RASTER_WIDTH_PIXELS = 5_000
PDF_MAX_RASTER_HEIGHT_PIXELS = 5_000
PDF_MAX_RASTER_PIXELS = 20_000_000
OCR_MAX_STDOUT_BYTES = TEXT_MAX_CODEPOINTS * 4
LOCAL_TOOL_MAX_STDERR_BYTES = 64 * 1024

AUDIO_TOOL_TIMEOUT_SECONDS = 180
ASR_TIMEOUT_SECONDS = 20 * 60
AUDIO_PCM_SAMPLE_RATE = 16_000
AUDIO_PCM_CHANNELS = 1
AUDIO_PCM_SAMPLE_BYTES = 2
NORMALIZED_WAV_HEADER_MAX_BYTES = 4_096
NORMALIZED_AUDIO_MAX_BYTES = (
    AUDIO_MAX_DURATION_SECONDS
    * AUDIO_PCM_SAMPLE_RATE
    * AUDIO_PCM_CHANNELS
    * AUDIO_PCM_SAMPLE_BYTES
    + NORMALIZED_WAV_HEADER_MAX_BYTES
)
LOCAL_TOOL_MAX_STDOUT_BYTES = 256 * 1024
ASR_MAX_STDOUT_BYTES = 512 * 1024
